# 1. LA CONEXIÓN A TU NUBE EN RAILWAY (¡Aquí está el problema!)
spring.datasource.url=jdbc:postgresql://postgres:uAMnrCjJYAtRcvEwDKaeDnMRlnqfRQNR@postgres.railway.internal:5432/railway

# 2. CONFIGURACIONES DE HIBERNATE Y JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 3. EL PUERTO DE TU SERVIDOR
server.port=8080