# 1. URL LOCAL PARA MYSQL
# Reemplaza 'tu_nombre_de_bd' por el nombre del esquema/database que creaste en Workbench
spring.datasource.url=jdbc:mysql://localhost:3306/yupi_pos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# 2. TUS CREDENCIALES LOCALES (Root)
spring.datasource.username=root
spring.datasource.password=root

# 3. CONFIGURACIONES DE HIBERNATE (Cambiado a MySQL)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# IMPORTANTE: Cambiamos el dialecto de PostgreSQL a MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 4. EL PUERTO DEL SERVIDOR (Se mantiene igual)
server.port=8080